require:
  - standard

plugins:
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  DisabledByDefault: true

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/request/**/*
