---
x-conditions:
  healthy: &healthy
    condition: service_healthy
  started: &started
    condition: service_started

services:
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis:/data

  rails:
    build:
      context: rails
      target: development
      dockerfile: Dockerfile
    command: "bin/rails server"
    depends_on:
      seaweed-init: *started
    links:
      - vite-rails
      - seaweed
    volumes:
      - ./rails:/srv/cast
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6700"]
    ports:
      - 6700:6700
    environment:
      SPACES_ENDPOINT: http://seaweed:8333/
      SPACES_HOST: http://localhost:8334/casts/
      VITE_RUBY_HOST: vite

  vite-rails:
    build:
      context: rails
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./rails:/srv/cast
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    command: bin/vite dev

  seaweed:
    image: chrislusf/seaweedfs
    ports:
      - "8334:8333"
    volumes:
      - seaweed:/data
    command: mini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8333/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      AWS_ACCESS_KEY_ID: ASDF123456
      AWS_SECRET_ACCESS_KEY: RANDOMHASH7899

  seaweed-init:
    image: amazon/aws-cli
    depends_on:
      seaweed:
        condition: service_healthy
    restart: "no"
    entrypoint: /bin/sh
    command: /app/bin/seaweed-init
    environment:
      AWS_ACCESS_KEY_ID: ASDF123456
      AWS_SECRET_ACCESS_KEY: RANDOMHASH7899
    volumes:
      - ./bin/seaweed-init:/app/bin/seaweed-init:ro
      - ./db/spaces/casts:/db/spaces/casts:ro

volumes:
  redis:
  seaweed:
