# Name of your application. Used to uniquely configure containers.
service: cast

servers:
  web:

env:
  clear:
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY

# Credentials for your image host.
registry:
  server: registry.digitalocean.com
  username: cflipse@gmail.com

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

proxy:
  app_port: 6700
  healthcheck:
    path: /
    interval: 5

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /srv/cast/public/vite
