# Name of the container image.
image: bwoa/casts

# Deploy to these servers.
servers:
  web:
    hosts:
      - waverly.athas.org

env:
  clear:
    RAILS_ENV: production
    OMNIAUTH_REDIRECT_URI: "https://cast.athas.org/auth/google_oauth2/callback"
