# Name of your application. Used to uniquely configure containers.
service: cast

servers:
  web:
  workers:
    cmd: sidekiq

env:
  secret:
    - RAILS_MASTER_KEY

# Credentials for your image host.
registry:
  server: registry.digitalocean.com
  username: cflipse@gmail.com

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  multiarch: false

# Configure custom arguments for Traefik
traefik:
  args:
    accesslog: true
    accesslog.format: json
    entryPoints.web.address: ":80"

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
   path: /up
   port: 6700

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /srv/cast/public/vite
