require:
  - standard

plugins:
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  DisabledByDefault: true
  TargetRubyVersion: 4.0
  TargetRailsVersion: 8.0

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/request/**/*
